<?php

/**
 * igCombo Demo
 * igCombo デモ用 REST API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Contracts\Routing\ResponseFactory;

class Combo1Api extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation getSamples
     *
     * サンプルデータ取得.
     *
     *
     * @return Http response
     */
    public function getSamples()
    {
        $input = Request::all();
        $header = Request::header();

        $count = DB::table('sample')->select('id')->count();
        $query = DB::table('sample')->orderBy('id', 'asc');

        if (is_array($input) && array_key_exists('$top', $input)) {
            $query->limit(intval($input['$top']));
        }
        if (is_array($input) && array_key_exists('$skip', $input)) {
            $query->offset(intval($input['$skip']));
        }

        return response()->stream(function () use ($count, $query) {
            $stream = fopen('php://output', 'w');
            fwrite($stream, '{');
            fwrite($stream, '"count":'.$count);
            fwrite($stream, ',"results":[');
            $idx = 0;
            foreach (
                $query->select('id', 'title', 'author', 'text')
                ->cursor() as $record
            ) {
                if ($idx++ > 0) fwrite($stream, ',');
                fwrite($stream, json_encode([
                    "id"=>intval($record->id),
                    "title"=>$record->title,
                    "author"=>$record->author,
                    "text"=>$record->text
                ], JSON_UNESCAPED_UNICODE));
            }
            fwrite($stream, ']');
            fwrite($stream, '}');
            fclose($stream);
        }, 
        200,
        [
            'Content-Type' => 'text/json; charset=utf-8',
            'Access-Control-Allow-Origin' => array_key_exists('origin', $header) ? $header['origin'] : '*'
        ]);
    }
}
